---
- name: Ensure containerd config directory exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'
  become: yes

- name: Render containerd config.toml with ghcr.io credentials
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  notify: restart k3s
  become: yes

- name: Reload systemd and restart k3s
  ansible.builtin.systemd:
    daemon_reload: yes
    name: k3s
    state: restarted
    enabled: yes
  become: yes
  when: restart_k3s | default(true)  
